# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south2-docker.pkg.dev/amplified-asset-426508-e7/my-docker-repo/backend:latest', './backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south2-docker.pkg.dev/amplified-asset-426508-e7/my-docker-repo/frontend:latest', './frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south2-docker.pkg.dev/amplified-asset-426508-e7/my-docker-repo/backend:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south2-docker.pkg.dev/amplified-asset-426508-e7/my-docker-repo/frontend:latest']
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster'
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south2-a'
    args: ['apply', '-f', './kubernetes-manifests/backend-deployment.yaml']
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster'
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south2-a'
    args: ['apply', '-f', './kubernetes-manifests/backend-service.yaml']
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster'
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south2-a'
    args: ['apply', '-f', './kubernetes-manifests/frontend-deployment.yaml']
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster'
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south2-a'
    args: ['apply', '-f', './kubernetes-manifests/frontend-service.yaml']
images:
  - 'asia-south2-docker.pkg.dev/amplified-asset-426508-e7/my-docker-repo/backend:latest'
  - 'asia-south2-docker.pkg.dev/amplified-asset-426508-e7/my-docker-repo/frontend:latest'

